### ISSUE TITLE
Appropriate translated equations in adoc documents

### ISSUE THREAD

**Issue by jbernalr** [APillekeit/fmi-standard#1]
For completness: the build proces described in CONTRIBUTING.adoc using Ruby and asciidoctor gems won't produce an output with appropriate translated equations (currently using latexmath). Should we extend the description on how to do this? (Im not sure if this is possiblie in html)
Or should we translate the equations to texmath or similar? @t-sommer what do you think?

**Comment by t-sommer** [comment]
Why don't you use the Docker image?

**Comment by jbernalr** [comment]
I was not aware this is possible with Docker and not with Ruby . I will try out Docker, but if Ruby is not a complete solution for our document exporting needs, shouldn't we remove it from the build instructions?

**Comment by t-sommer** [comment]
The Docker image uses the AsciiDoctor Ruby gem internally. The old "Ruby way" is still there for people that cannot use Docker (for whatever reason).

**Comment by jbernalr** [comment]
Using Ruby a number of aditional gems are required to generate the latex equations, but most prominently what did the job for me was to install the asciidoctor-latex gem, then doing something like this: 
`asciidoctor-latex -B . -b html5 docs/fmi_specification.adoc`
The point between flags -B and -b is just to indicate my current directory.

**Comment by t-sommer** [comment]
@jbernalr, can you make a PR to update the documentation?

**Comment by jbernalr** [comment]
@t-sommer, now the changes are into FCP007. Not sure how to cherry pick only the changes made in `CONTRIBUTING.adoc` and neglect all other commits. Can you pull only this?

**Comment by jbernalr** [comment]
closing this since alternatives to generate html specification via CI are available
