### ISSUE TITLE
Can an FMU call intermediateStepFinished for simulation times after the next CP time that is set by the master?

### ISSUE THREAD

**Issue by APillekeit** [APillekeit/fmi-standard#3]
Option 1: No – FMU would have to stop computation close to CP
Option 2: Yes – FMU and Master could exchange information from the „simulation future“

Needs more discussion
This is related to the new state machine: https://github.com/modelica/fmi-standard/issues/535#issuecomment-487592883

**Comment by robbr48** [comment]
With option 1, the FMU can still simulate past the CP by e.g. extrapolating variables internally. 

I think the key issue with option 2 is what will happen if the FMU asks for intermediate input variables past the CP, but there are none available in the master. If the FMU expects variables to be updated even though they are not, it can cause problems for the solver. Perhaps this can be solved by some return code of the callback function, which informs the FMU that the inputs are unavailable.

Option 1 make things easier in my opinion. If the FMU wants to compute past the next CP, it will know that the callback is not available.

These opinions of course only takes IVA into account. For the other uses of the callback, it makes no sense to call it after the next CP, maybe with exception for IOVs.

**Comment by APillekeit** [comment]
Comments from WG FCP007/010/015 WebEx 14 June 2019

The fmi3intermediateStepFinished() can only be called for intermediateStepTime that lie in the intvervalls for the closed intervall [CommunicationPoint, CommunicationPoint + CommunicationStepSize] otherwise the master sets the function returnvalue to fmi3Error.  

Reason: This might be changed in the future, but currently this not properly discussed and we lack experience with such a feature.    

Additional discussion: It should be defined which function return values shall be provided by the master in certain situations e.g. if no intermediate input values are available. And how the FMU sould continue in such situations.
Suggestion is: Master can return fmi3Discard if it can not provide required values. The FMU can decide on how to continue. It should be discussed in FMI Design Meeting in Renningen what happens when it returns fmi3Error.

**Comment by jbernalr** [comment]
According to the desicion made in Renningen 2019, the answer to this is: 

Yes, but not prior to `fmi3IntermediateUpdate` with `intermediateStepFinished=true`

(see minutes of the meeting as well)

**Comment by robbr48** [comment]
Correction: The decision in Renningen was that it is NOT allowed to call the function after the next communication point time.

In conclusion: 
- `fmi3IntermediateUpdate` shall only be called in the closed interval [CommunicationPoint, CommunicationPoint + CommunicationStepSize] 
- `fmi3IntermediateUpdate` shall not be called prior to a previous call to `fmi3IntermediateUpdate` with `intermediateStepFinished=true`
